from __future__ import annotations

from drpo.methods._baseline_loader import load_baseline_module

_reward_gradient = load_baseline_module("vggflow", "reward_gradient.py")

DifferentiableAestheticReward = _reward_gradient.DifferentiableAestheticReward
DifferentiablePickScoreReward = _reward_gradient.DifferentiablePickScoreReward
clip_gradient_by_norm = _reward_gradient.clip_gradient_by_norm
compute_pickscore_reward_gradient = _reward_gradient.compute_pickscore_reward_gradient
eta_multiplier = _reward_gradient.eta_multiplier
